import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.scss";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import BodyClassHandler from "@/utils/BodyClassHandler";
import LayoutWrapper from "@/components/LayoutWrapper";

import { HeaderHeightProvider } from "@/context/HeaderHeightContext";

// const geistSans = Geist({
// 	variable: "--font-geist-sans",
// 	subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
// 	variable: "--font-geist-mono",
// 	subsets: ["latin"],
// });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				// className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				className="antialiased"
			>
				<BodyClassHandler />
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<HeaderHeightProvider>
						<div className="bg-bgbody bg-fixed bg-cover relative z-10">
							<Header />
							<LayoutWrapper>{children}</LayoutWrapper>
						</div>
						<Footer />
					</HeaderHeightProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
